version: '2'
services:
  eurekaserver:
    build:
      context: ../EurekaServer
      dockerfile: Dockerfile
    #    image: eurekaserver:latest
    ports:
      - "8761:8761"
  database:
    image: postgres:9.5
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1q2w3e4r
    #      - POSTGRES_DB=eagle_eye_local
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  configserver:
    build:
      context: ../ConfigServer
      dockerfile: Dockerfile
    #    image: configserver:latest
    ports:
      - "8888:8888"
    environment:
      EUREKASERVER_URI: "http://eurekaserver:8761/eureka/"
      EUREKASERVER_PORT: "8761"
      ENCRYPT_KEY: "K0R@"

  memberserver:
    build:
      context: ../MemberServer
      dockerfile: Dockerfile
    #    image: memberserver:latest
    ports:
      - "8080:8080"
    environment:
      PROFILE: "default"
      SERVER_PORT: "8080"
      EUREKASERVER_URI: "http://eurekaserver:8761/eureka/"
      CONFIGSERVER_URI: "http://configserver:8888"
      AUTHSERVER_URI: "http://authserver:8901/auth/user"
      ZIPKIN_URI: "http://zipkin:9411"
      KAFKASERVER_URI: "kafkaserver"
      ZKSERVER_URI: "zookeeper"
      EUREKASERVER_PORT: "8761"
      DATABASESERVER_PORT: "5432"
      CONFIGSERVER_PORT: "8888"
      AUTHSERVER_PORT: "8091"
      ZUULSERVER_PORT: "5555"
      KAFKASERVER_PORT: "2181"
      ZIPKIN_PORT: "9411"
      ENCRYPT_KEY: "K0R@"

  itemserver:
    build:
      context: ../ItemServer
      dockerfile: Dockerfile
    #    image: itemserver:latest
    ports:
      - "8081:8081"
    environment:
      PROFILE: "default"
      EUREKASERVER_URI: "http://eurekaserver:8761/eureka/"
      CONFIGSERVER_URI: "http://configserver:8888"
      AUTHSERVER_URI: "http://authserver:8901/auth/user"
      ZIPKIN_URI: "http://zipkin:9411"
      KAFKASERVER_URI: "kafkaserver"
      ZKSERVER_URI: "zookeeper"
      SERVER_PORT: "8081"
      EUREKASERVER_PORT: "8761"
      DATABASESERVER_PORT: "5432"
      CONFIGSERVER_PORT: "8888"
      AUTHSERVER_PORT: "8091"
      ZUULSERVER_PORT: "5555"
      KAFKASERVER_PORT: "2181"
      ZIPKIN_PORT: "9411"
      ENCRYPT_KEY: "K0R@"

  orderserver:
    build:
      context: ../OrderServer
      dockerfile: Dockerfile
    #    image: orderserver:latest
    ports:
      - "8082:8082"
    environment:
      PROFILE: "default"
      SERVER_PORT: "8082"
      EUREKASERVER_URI: "http://eurekaserver:8761/eureka/"
      CONFIGSERVER_URI: "http://configserver:8888"
      AUTHSERVER_URI: "http://authserver:8901/auth/user"
      KAFKASERVER_URI: "kafkaserver"
      ZKSERVER_URI: "zookeeper"
      ZIPKIN_URI: "http://zipkin:9411"
      EUREKASERVER_PORT: "8761"
      DATABASESERVER_PORT: "5432"
      CONFIGSERVER_PORT: "8888"
      AUTHSERVER_PORT: "8091"
      ZUULSERVER_PORT: "5555"
      KAFKASERVER_PORT: "2181"
      ZIPKIN_PORT: "9411"
      ENCRYPT_KEY: "K0R@"

  zuulserver:
    build:
      context: ../ZuulServer
      dockerfile: Dockerfile
    #    image: zuulserver:latest
    ports:
      - "5555:5555"
    environment:
      PROFILE: "default"
      SERVER_PORT: "5555"
      CONFIGSERVER_URI: "http://configserver:8888"
      EUREKASERVER_URI: "http://eurekaserver:8761/eureka/"
      ZIPKIN_URI: "http://zipkin:9411"
      EUREKASERVER_PORT: "8761"
      DATABASESERVER_PORT: "5432"
      CONFIGSERVER_PORT: "8888"

  authserver:
    build:
      context: ../AuthServer
      dockerfile: Dockerfile
    ports:
      - "8901:8901"
    environment:
      PROFILE: "default"
      SERVER_PORT: "8901"
      EUREKASERVER_URI: "http://eurekaserver:8761/eureka/"
      CONFIGSERVER_URI: "http://configserver:8888"
      EUREKASERVER_PORT: "8761"
      DATABASESERVER_PORT: "5432"
      CONFIGSERVER_PORT: "8888"
      ENCRYPT_KEY: "K0R@"

  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    restart: always
    ports:
      - "2181:2181"

  kafkaserver:
    image: wurstmeister/kafka
    container_name: kafka
    restart: always
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    links:
      - zookeeper:zookeeper
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  zipkin:
    image: openzipkin/zipkin
    ports:
      - "9411:9411"